CREATE TABLE [dbo].[SafetyEvents] (
    [CreatedOn]               DATETIME2 (7)  NOT NULL,
    [CreatedBy]               NVARCHAR (50)  NOT NULL,
    [ModifiedOn]              DATETIME2 (7)  NOT NULL,
    [ModifiedBy]              NVARCHAR (50)  NOT NULL,
    [EventId]                 INT            IDENTITY (1, 1) NOT NULL,
    [EventType]               NVARCHAR (50)  NOT NULL,
    [EventStatus]             NVARCHAR (50)  NOT NULL,
    [ReportedBy]              NVARCHAR (MAX) NULL,
    [ReportedOn]              DATETIME2 (7)  NOT NULL,
    [EventDate]               DATETIME2 (7)  NOT NULL,
    [EventTime]               DATETIME2 (7)  NOT NULL,
    [EmployeeId]              NVARCHAR (MAX) NULL,
    [JobTitle]                NVARCHAR (50)  NOT NULL,
    [Shift]                   NVARCHAR (50)  NOT NULL,
    [WhatHappened]            NVARCHAR (MAX) NOT NULL,
    [IsInjury]                BIT            NOT NULL,
    [IsIllness]               BIT            NOT NULL,
    [HoursWorkedPrior]        TINYINT        NOT NULL,
    [InitialCategory]         NVARCHAR (50)  NOT NULL,
    [ResultingCategory]       NVARCHAR (50)  NOT NULL,
    [Division]                NVARCHAR (50)  NULL,
    [Site]                    NVARCHAR (50)  NULL,
    [Area]                    NVARCHAR (50)  NULL,
    [Department]              NVARCHAR (50)  NULL,
    [LocaleRegion]            NVARCHAR (50)  NULL,
    [LocaleSite]              NVARCHAR (50)  NULL,
    [LocalePlant]             NVARCHAR (50)  NULL,
    [LocalePlantArea]         NVARCHAR (50)  NULL,
    [WorkEnvironment]         NVARCHAR (50)  NOT NULL,
    [NatureOfEnjury]          NVARCHAR (50)  NOT NULL,
    [BodyPart]                NVARCHAR (50)  NOT NULL,
    [FirstAidType]            NVARCHAR (50)  NULL,
    [OffPlantMedicalFacility] NVARCHAR (50)  NULL,
    [MaterialInvolved]        NVARCHAR (50)  NULL,
    [EquipmentInvolved]       NVARCHAR (50)  NULL,
    [LostTime]                BIT            NOT NULL,
    [FirstAid]                BIT            NOT NULL,
    [Transported]             BIT            NOT NULL,
    [ER]                      BIT            NOT NULL,
    [PassedPOET]              BIT            NOT NULL,
    [RecordedOnVideo]         BIT            NOT NULL,
    [CameraId]                INT            NULL,
    [VideoStartRef]           DATETIME2 (7)  NULL,
    [VideoEndRef]             DATETIME2 (7)  NULL,
    [DepartmentId]            INT            DEFAULT ((0)) NOT NULL,
    [LocaleId]                INT            DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_SafetyEvents] PRIMARY KEY CLUSTERED ([EventId] ASC)
);

