export const ADD_ERROR = 'ADD_ERROR';
export const REMOVE_ERROR = 'REMOVE_ERROR';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const LOAD_SAFETY_INCIDENTS = 'LOAD_SAFETY_INCIDENTS';
// export const LOAD_LOOKUP_DATA = 'LOAD_LOOKUP_DATA'; 
// export const LOAD_LOGICAL_TREE = 'LOAD_LOGICAL_TREE'; 
// export const LOAD_PHYSICAL_TREE = 'LOAD_PHYSICAL_TREE';
export const LOAD_LOGICAL_HIERARCHIES = 'LOAD_LOGICAL_HIERARCHIES';
export const LOAD_PHYSICAL_HIERARCHIES = 'LOAD_PHYSICAL_HIERARCHIES';
export const LOAD_LOGICAL_HIERARCHY_ATTRIBUTES = 'LOAD_LOGICAL_HIERARCHY_ATTRIBUTES';
export const LOAD_PHYSICAL_HIERARCHY_ATTRIBUTES = 'LOAD_PHYSICAL_HIERARCHY_ATTRIBUTES';
export const LOAD_EMPLOYEES = 'LOAD_EMPLOYEES';


