export const ADD_ERROR = 'ADD_ERROR';
export const REMOVE_ERROR = 'REMOVE_ERROR';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const LOAD_SAFETY_INCIDENTS = 'LOAD_SAFETY_INCIDENTS';
export const LOAD_LOOKUP_DATA = 'LOAD_LOOKUP_DATA'; 